// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mumbi.Infrastucture.Context;

namespace Mumbi.Infrastucture.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210701191348_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mumbi.Domain.Entities.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Action");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.ActionChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActionId")
                        .HasColumnType("int")
                        .HasColumnName("Action_Id");

                    b.Property<bool>("CheckedFlag")
                        .HasColumnType("bit");

                    b.Property<int>("ChildId")
                        .HasColumnType("int")
                        .HasColumnName("Child_Id");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("ChildId");

                    b.ToTable("Action_Child");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.ChildHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChildId")
                        .HasColumnType("int")
                        .HasColumnName("Child_Id");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("HeadCircumference")
                        .HasColumnType("float");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Child_History");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.ChildInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("AvgMilk")
                        .HasColumnType("float");

                    b.Property<string>("Birthday")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("BornFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("EstimatedBornDate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Fingertips")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("HeadCircumference")
                        .HasColumnType("float");

                    b.Property<byte?>("HeadVortex")
                        .HasColumnType("tinyint");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<double?>("HourSleep")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("MomId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Mom_Id");

                    b.Property<string>("Nickname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RhBloodGroup")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MomId");

                    b.ToTable("Child_Info");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.DadInfo", b =>
                {
                    b.Property<string>("MomId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Mom_Id");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("Phonenumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("RhBloodGroup")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("MomId")
                        .HasName("PK_Dad");

                    b.ToTable("Dad_Info");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Diary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ApprovedFlag")
                        .HasColumnType("bit");

                    b.Property<int>("ChildId")
                        .HasColumnType("int")
                        .HasColumnName("Child_Id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DiaryContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Diary");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Guidebook", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<short?>("EstimatedFinishTime")
                        .HasColumnType("smallint");

                    b.Property<string>("GuidebookContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuidebookTypeId")
                        .HasColumnType("int")
                        .HasColumnName("GuidebookType_Id");

                    b.Property<string>("ImageUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GuidebookTypeId");

                    b.ToTable("Guidebook");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.GuidebookMom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GuidebookId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Guidebook_Id");

                    b.Property<string>("MomId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Mom_Id");

                    b.HasKey("Id");

                    b.HasIndex("GuidebookId");

                    b.HasIndex("MomId");

                    b.ToTable("Guidebook_Mom");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.GuidebookType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Guidebook_Type");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.InjectionSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChildId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Child_Id");

                    b.Property<bool?>("InjectedFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("InjectionDate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MomId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Mom_Id");

                    b.Property<string>("NextInjectionDate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte?>("OrderOfInjection")
                        .HasColumnType("tinyint");

                    b.Property<string>("Phonenumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int>("VaccineId")
                        .HasColumnType("int")
                        .HasColumnName("Vaccine_Id");

                    b.HasKey("Id");

                    b.HasIndex("MomId");

                    b.HasIndex("VaccineId");

                    b.ToTable("InjectionSchedule");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.MomInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DadId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Dad_Id");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("RhBloodGroup")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Mom_Info");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.News", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<short?>("EstimateFinishTime")
                        .HasColumnType("smallint");

                    b.Property<string>("ImageUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("NewsContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("Type_Id");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.NewsMom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MomId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Mom_Id");

                    b.Property<string>("NewsId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("News_Id");

                    b.HasKey("Id");

                    b.HasIndex("MomId");

                    b.HasIndex("NewsId");

                    b.ToTable("News_Mom");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.NewsType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("News_Type");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("NotificationContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.PregnancyActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChildId")
                        .HasColumnType("int")
                        .HasColumnName("Child_Id");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("FinishedFlag")
                        .HasColumnType("bit");

                    b.Property<string>("MediaFileUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("MediaFileURL");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("Type_Id");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("TypeId");

                    b.ToTable("PregnancyActivity");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.PregnancyActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("DelFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("SuitableAge")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PregnancyActivity_Type");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.PregnancyInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("BiparietalDiameter")
                        .HasColumnType("float");

                    b.Property<int>("ChildId")
                        .HasColumnType("int")
                        .HasColumnName("Child_Id");

                    b.Property<double?>("FemurLength")
                        .HasColumnType("float");

                    b.Property<double?>("FetalHeartRate")
                        .HasColumnType("float");

                    b.Property<double?>("MotherWeight")
                        .HasColumnType("float");

                    b.Property<string>("PregnancyWeek")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Pregnancy_Info");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("EnabledFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Frequency")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("time(0)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("User_Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reminder");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.StandardIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<double>("MaxValue")
                        .HasColumnType("float");

                    b.Property<double>("MinValue")
                        .HasColumnType("float");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("StandardIndex");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("User_Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Tooth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChildId")
                        .HasColumnType("int")
                        .HasColumnName("Child_Id");

                    b.Property<string>("GrowTime")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("GrownFlag")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Position")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Tooth");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Role_Id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.UserInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Birthday")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("Phonenumber")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("User_Info");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.UsersNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NotificationId")
                        .HasColumnType("int")
                        .HasColumnName("Notification_Id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("User_Id");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersNotification");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Disease")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProducingCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Vaccine");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.ActionChild", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.Action", "Action")
                        .WithMany("ActionChildren")
                        .HasForeignKey("ActionId")
                        .HasConstraintName("FK_ActionChild_Action")
                        .IsRequired();

                    b.HasOne("Mumbi.Domain.Entities.ChildInfo", "Child")
                        .WithMany("ActionChildren")
                        .HasForeignKey("ChildId")
                        .HasConstraintName("FK_Action_Child_Child_Info")
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.ChildHistory", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.ChildInfo", "Child")
                        .WithMany("ChildHistories")
                        .HasForeignKey("ChildId")
                        .HasConstraintName("FK_Child_History_Child_Info")
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.ChildInfo", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.MomInfo", "Mom")
                        .WithMany("ChildInfos")
                        .HasForeignKey("MomId")
                        .HasConstraintName("FK_Child_Info_Mom_Info")
                        .IsRequired();

                    b.Navigation("Mom");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.DadInfo", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.MomInfo", "Mom")
                        .WithOne("DadInfo")
                        .HasForeignKey("Mumbi.Domain.Entities.DadInfo", "MomId")
                        .HasConstraintName("FK_Dad_Info_Mom_Info")
                        .IsRequired();

                    b.Navigation("Mom");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Diary", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.ChildInfo", "Child")
                        .WithMany("Diaries")
                        .HasForeignKey("ChildId")
                        .HasConstraintName("FK_Diary_Child_Info")
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Guidebook", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.GuidebookType", "GuidebookType")
                        .WithMany("Guidebooks")
                        .HasForeignKey("GuidebookTypeId")
                        .HasConstraintName("FK_Guidebook_GuildbookType");

                    b.Navigation("GuidebookType");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.GuidebookMom", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.Guidebook", "Guidebook")
                        .WithMany("GuidebookMoms")
                        .HasForeignKey("GuidebookId")
                        .HasConstraintName("FK_GuidebookMom_Guidebook")
                        .IsRequired();

                    b.HasOne("Mumbi.Domain.Entities.MomInfo", "Mom")
                        .WithMany("GuidebookMoms")
                        .HasForeignKey("MomId")
                        .HasConstraintName("FK_Guidebook_Mom_Mom_Info")
                        .IsRequired();

                    b.Navigation("Guidebook");

                    b.Navigation("Mom");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.InjectionSchedule", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.MomInfo", "Mom")
                        .WithMany("InjectionSchedules")
                        .HasForeignKey("MomId")
                        .HasConstraintName("FK_InjectionSchedule_Mom_Info");

                    b.HasOne("Mumbi.Domain.Entities.Vaccine", "Vaccine")
                        .WithMany("InjectionSchedules")
                        .HasForeignKey("VaccineId")
                        .HasConstraintName("FK_InjectionSchedule_Vaccine1")
                        .IsRequired();

                    b.Navigation("Mom");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.MomInfo", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.User", "IdNavigation")
                        .WithOne("MomInfo")
                        .HasForeignKey("Mumbi.Domain.Entities.MomInfo", "Id")
                        .HasConstraintName("FK_Mom_Info_Users")
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.News", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.NewsType", "Type")
                        .WithMany("News")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_News_NewsType");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.NewsMom", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.MomInfo", "Mom")
                        .WithMany("NewsMoms")
                        .HasForeignKey("MomId")
                        .HasConstraintName("FK_News_Mom_Mom_Info")
                        .IsRequired();

                    b.HasOne("Mumbi.Domain.Entities.News", "News")
                        .WithMany("NewsMoms")
                        .HasForeignKey("NewsId")
                        .HasConstraintName("FK_NewsMom_News")
                        .IsRequired();

                    b.Navigation("Mom");

                    b.Navigation("News");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.PregnancyActivity", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.ChildInfo", "Child")
                        .WithMany("PregnancyActivities")
                        .HasForeignKey("ChildId")
                        .HasConstraintName("FK_PregnancyActivity_Child_Info");

                    b.HasOne("Mumbi.Domain.Entities.PregnancyActivityType", "Type")
                        .WithMany("PregnancyActivities")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK_PregnancyActivity_PregnancyActivity_Type");

                    b.Navigation("Child");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.PregnancyInfo", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.ChildInfo", "Child")
                        .WithMany("PregnancyInfos")
                        .HasForeignKey("ChildId")
                        .HasConstraintName("FK_Pregnancy_Info_Child_Info")
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.User", "User")
                        .WithMany("Reminders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Reminder_Users")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Token", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Token_Account")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Tooth", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.ChildInfo", "Child")
                        .WithMany("Teeth")
                        .HasForeignKey("ChildId")
                        .HasConstraintName("FK_Tooth_Child_Info")
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.User", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Users_Role")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.UserInfo", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.User", "IdNavigation")
                        .WithOne("UserInfo")
                        .HasForeignKey("Mumbi.Domain.Entities.UserInfo", "Id")
                        .HasConstraintName("FK_Users_Info_Users")
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.UsersNotification", b =>
                {
                    b.HasOne("Mumbi.Domain.Entities.Notification", "Notification")
                        .WithMany("UsersNotifications")
                        .HasForeignKey("NotificationId")
                        .HasConstraintName("FK_UsersNotification_Notification")
                        .IsRequired();

                    b.HasOne("Mumbi.Domain.Entities.User", "User")
                        .WithMany("UsersNotifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UsersNotification_Users")
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Action", b =>
                {
                    b.Navigation("ActionChildren");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.ChildInfo", b =>
                {
                    b.Navigation("ActionChildren");

                    b.Navigation("ChildHistories");

                    b.Navigation("Diaries");

                    b.Navigation("PregnancyActivities");

                    b.Navigation("PregnancyInfos");

                    b.Navigation("Teeth");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Guidebook", b =>
                {
                    b.Navigation("GuidebookMoms");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.GuidebookType", b =>
                {
                    b.Navigation("Guidebooks");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.MomInfo", b =>
                {
                    b.Navigation("ChildInfos");

                    b.Navigation("DadInfo");

                    b.Navigation("GuidebookMoms");

                    b.Navigation("InjectionSchedules");

                    b.Navigation("NewsMoms");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.News", b =>
                {
                    b.Navigation("NewsMoms");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.NewsType", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Notification", b =>
                {
                    b.Navigation("UsersNotifications");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.PregnancyActivityType", b =>
                {
                    b.Navigation("PregnancyActivities");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.User", b =>
                {
                    b.Navigation("MomInfo");

                    b.Navigation("Reminders");

                    b.Navigation("Tokens");

                    b.Navigation("UserInfo");

                    b.Navigation("UsersNotifications");
                });

            modelBuilder.Entity("Mumbi.Domain.Entities.Vaccine", b =>
                {
                    b.Navigation("InjectionSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
